embed: 
	export CORENLP_HOME=/Users/roy/Documents/ML/dcn-project/stanford-corenlp-full-2018-10-05/ && python3 preprocess_data.py

tokenize:
	export CORENLP_HOME=/Users/roy/Documents/ML/dcn-project/stanford-corenlp-full-2018-10-05/ && python3 tokenize_data.py

tokenize_data_elise:
	export CORENLP_HOME=/Users/roy/Documents/ML/dcn-project/stanford-corenlp-full-2018-10-05/ && python3 tokenize_data_elise.py
