# Defaults/constants.

BATCH_SIZE = 64
DROPOUT = 0.3
HIDDEN_DIM = 200  # Denoted by 'l' in the paper.
MAX_ITER = 4
MAXOUT_POOL_SIZE = 16
MAX_CONTEXT_LEN = 600
MAX_GRAD_NORM = 0.5
MAX_QUESTION_LEN = 30
REG_LAMBDA = 0.1
TEST_DCN_MODEL_WITH_CPU = False
_PAD = b"<pad>"
_UNK = b"<unk>"
_START_VOCAB = [_PAD, _UNK]
PAD_ID = 0
UNK_ID = 1
